In [1]:
!pip install ThaiAddressParser

Requirement already satisfied: ThaiAddressParser in c:\users\10\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied: requests in c:\users\10\anaconda3\lib\site-packages (from ThaiAddressParser) (2.28.1)
Requirement already satisfied: tqdm in c:\users\10\anaconda3\lib\site-packages (from ThaiAddressParser) (4.64.1)
Requirement already satisfied: bs4 in c:\users\10\anaconda3\lib\site-packages (from ThaiAddressParser) (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\10\anaconda3\lib\site-packages (from bs4->ThaiAddressParser) (4.11.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\10\anaconda3\lib\site-packages (from requests->ThaiAddressParser) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\10\anaconda3\lib\site-packages (from requests->ThaiAddressParser) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\10\anaconda3\lib\site-packages (from requests->ThaiAddressParser) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\10\anaconda3\lib\site-packages (from requests->ThaiAddressParser) (2.0.4)
Requirement already satisfied: colorama in c:\users\10\anaconda3\lib\site-packages (from tqdm->ThaiAddressParser) (0.4.6)
Requirement already satisfied: soupsieve>1.2 in c:\users\10\anaconda3\lib\site-packages (from beautifulsoup4->bs4->ThaiAddressParser) (2.3.2.post1)

In [2]:
import __init__

In [3]:
import ThaiAddressParser
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
import re

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
oridata = pd.read_excel("SHOPnLAZ.xlsx",sheet_name="SHOPEE")

In [7]:
def censor_name(df, column_name, censor_char='*'):
    censored_df = df.copy()
    censored_df[column_name] = censored_df[column_name].apply(
        lambda x: ' '.join(
            [word if index != 2 else censor_char * len(word) for index, word in enumerate(x.split())]
        )
    )
    return censored_df

In [8]:
censored_column = 'text'
censored_data = censor_name(oridata, censored_column)

In [9]:
censored_data

,order_number,text
0,Shopee Order No. 221222BTVHAWY8,ผู้รับ(TO) น.ส.ปณิธาน ****** 47/20 ซ.ร่มโพธิ ถ...
1,Shopee Order No. 221222C3X56QEB,ผู้รับ(TO) ทวิรินทร์ ************** 406/500 คอ...
2,Shopee Order No. 221222AX1H2UTX,ผู้รับ(TO) ชมพูนุช ********* 73/224 I Condo pl...
3,Shopee Order No. 221222C3X56QEB,ผู้รับ(TO) ทวิรินทร์ ************** 406/500 คอ...
4,Shopee Order No. 221222AX1H2UTX,ผู้รับ(TO) ชมพูนุช ********* ซ.สุขาอุปถัมภ์ 9 ...
5,Shopee Order No. 221222BTVHAWY8,ผู้รับ(TO) น.ส.ปณิธาน ****** 47/20 ซ.ร่มโพธิ ถ...
6,Shopee Order No. 221228S31MWMBB,ผู้รับ(TO) รุ้งเงิน ******** ซอยนพรัตน์24 หมู่...
7,Shopee Order No. 221216S7GFUD8J,ผู้รับ(TO) คุณดา *** ถนนพระราม 2แขวงแสมดำ เขตบ...
8,Shopee Order No. 221228RY260PFR,ผู้รับ(TO) Kirati ***** 202/166 ไลฟ์บางกอกบูเล...
9,Shopee Order No. 221228S31MWMEB,ผู้รับ(TO) รุ้งเงิน ******** ซอยนพรัตน์24 หมู่...
10,Shopee Order No. 221228RY260PFR,ผู้รับ(TO) Kirati ***** 202/166 ไลฟ์บางกอกบูเล...
11,Shopee Order No. 2212181WAPAX9N,ผู้รับ(TO) Naowarat ******** บ้านเลขที่ 2 อาคา...
12,Shopee Order No. 221213J92K3P38,ผู้รับ(TO) โสมส่องหล้า ************ ศูนย์แพทยศ...
13,Shopee Order No. 2212181VAPAX9N,ผู้รับ(TO) Naowarat ******** บ้านเลขที่ 2 อาคา...
14,Shopee Order No. 221213J92K3P338,ผู้รับ(TO) โสมส่องหล้า ************ ศูนย์แพทยศ...
15,Shopee Order No. 221216S7GFUD8J,ผู้รับ(TO) คุณดา *** ถนนพระราม 2 แขวง เขตเสมดำ...
16,Shopee Order No. 221214KTJVWEKXE,"ผู้รับ(TO) Laddawan *** ซ.ราชวิถี34, เขตดุสิต,..."
17,Shopee Order No. 221214KTJVWEKXE,"ผู้รับ(TO) Laddawan *** ซ.ราชวิถี34, เขตดุสิต,..."
18,Shopee Order No. 221215PP87QQQ2,ผู้รับ(TO) ปราโมทย์ ******** 3 ซ.เชิงทะเล 16 ถ...
19,Shopee Order No. 221204RDTR5WGS,ผู้รับ(TO) บวรรัตน์ ******* คอนโด ไอดีโอ โมบิ ...
20,Shopee Order No. 221215PP87QQQ2,ผู้รับ(TO) ปราโมทย์ ******** 3 ซ.เชิงทะเล 16 ถ...
21,Shopee Order No. 2212060F0PY5XQ,ผู้รับ(TO) ประกายดาว ********** 283/283 คอนโดบ...
22,Shopee Order No. 221204RDTR!5WGS,(รับ(TO) บวรรัตน์ ******* อนโด ไอดีโอ โมบิ บาง...
23,Shopee Order No. 221203NGVP6517,ผู้รับ(TO) นัฎ ******* เบญจทรัพย์นคร โครงการ2 ...
24,Shopee Order No. 2212060F0PY5XQ,ผู้รับ (TO) ********* พุ่มประดับ 283/283 คอนโด...
25,Shopee Order No. 221203NGVP6517,ผู้รับ(TO) นัฎ ******* เบญจทรัพย์นคร โครงการ2 ...
26,Shopee Order No. 2212050U02245V,ผู้รับ(TO) ลลิตกร่ำชิต ***** หมู่บ้าน the star...
27,Shopee Order No. 2212060U02245V,ผู้รับ(TO) ลลิตกร ****** 66/62 หมู่บ้าน the st...
28,Shopee Order No. 22120600QMHD9N,ผู้รับ(TO) มนตรี *********** 66/84 ซ 7 หมู่บ้า...
29,Shopee Order No. 2212060U44NINQU,ผู้รับ(TO) ลลิตกรอ่ำชิต ******************** 6...
30,Shopee Order No. 22120600QMHD9N,ผู้รับ(TO) มนตรี *********** 66/84ซ.7 หมู่บ้าน...
31,Shopee Order No. 2212060U44NNQU,ผู้รับ(TO) ลลิตกรอ่ำชิต ***** หมู่บ้าน the sta...
32,Shopee Order.No. 2212073MWQXQMU,ผู้รับ(TO) อัญชนา *************** 72/43 กรุงเท...
33,Shopee Order No. 22120736W3874V,ผู้รับ(TO) ตรีรักษ์ *********** 230/6 ต.มหาชัย...
34,Shopee Order No. 2212073MWQXQMU,ผู้รับ(TO) อัญชนา *************** 72/43 ซ.อินท...
35,Shopee Order No. 22120736W3874V,ผู้รับ(TO) ตรีรักษ์ *********** 230/6 ต.มหาชัย...
36,Shopee Order No. 22120853S3B3WD,ผู้รับ(TO) อรจิรา **** หมู่2 ซอยวัดใหญ่ ตำบลใน...
37,Shopee Order No. 2212084DJ5DQAQ,ผู้รับ(TO) ปฏิภาณเปียคำ ****** 580/16 ซอยโพธิ์...
38,Shopee Order No. 2212084DJ5DQAQ,ผู้รับ(TO) ปฏิภาณเปียคำ ****** 580/16 ซอยโพธิ์...

In [10]:
df = oridata

In [11]:
df['text'] = oridata.text

In [12]:
#dfnew= df['text'].astype('string')

In [13]:
#string_data = df["text"].to_string(index=False)

#array_data = string_data.splitlines()
#print(array_data)

In [14]:
#dfnew.info()

In [15]:
df['OrderID'] = df['order_number'].str.extract(r'No.\s(.*)')
df['Platform'] = ''
df.loc[df['order_number'].str.contains('Shopee'), 'Platform'] = 'Shopee'
df.loc[df['order_number'].str.contains('Lazada'), 'Platform'] = 'Lazada'
#df['Name'] = df['text'].str.extract(r'\(TO\)\s(.+?)\s\d')
#df['ที่อยู่'] = df['text'].str.split('\s+').str[3:]

In [16]:
df = df.drop(columns = ['order_number'])

In [17]:
#ขั้นตอนการแยก splitdata

In [18]:
#from transformers import AutoTokenizer, AutoModelForTokenClassification
#tokenizer = AutoTokenizer.from_pretrained("pythainlp/thainer-corpus-v2-base-model")
#model = AutoModelForTokenClassification.from_pretrained("pythainlp/thainer-corpus-v2-base-model")

In [19]:
train = oridata['text'].to_frame()

In [20]:
def fix_span_error(words,ner):
    _ner = []
    _ner=ner
    _new_tag=[]
    for i,j in zip(words,_ner):
        #print(i,j)
        i=tokenizer.decode(i)
        if i.isspace() and j.startswith("B-"):
            j="O"
        if i=='' or i=='<s>' or i=='</s>':
            continue
        if i=="<_>":
            i=" "
        _new_tag.append((i,j))
    return _new_tag

In [21]:
def merge_person_names(tags):
    merged_names = []
    current_name = ""
    inside_name = False

    for tag in tags:
        word, entity = tag
        if entity == "B-PERSON" or entity == "I-PERSON":
            if current_name != "":
                merged_names.append(current_name)
            current_name = word
            inside_name = True
        else:
            if inside_name:
                merged_names.append(current_name)
                current_name = ""
                inside_name = False

    if current_name != "":
        merged_names.append(current_name)

    return "".join(merged_names)

In [22]:
dfmain = pd.DataFrame()
arrvalues = []

In [23]:
from transformers import AutoTokenizer
from transformers import AutoModelForTokenClassification
from pythainlp.tokenize import word_tokenize # pip install pythainlp
import torch
for index, row in train.iterrows():
    name="pythainlp/thainer-corpus-v2-base-model"
    tokenizer = AutoTokenizer.from_pretrained(name)
    model = AutoModelForTokenClassification.from_pretrained(name)

    sentence = row.to_string(index=False)
    cut=word_tokenize(sentence.replace(" ", "<_>"))
    inputs=tokenizer(cut,is_split_into_words=True,return_tensors="pt")

    ids = inputs["input_ids"]
    mask = inputs["attention_mask"]
    # forward pass
    outputs = model(ids, attention_mask=mask)
    logits = outputs[0]

    predictions = torch.argmax(logits, dim=2)
    predicted_token_class = [model.config.id2label[t.item()] for t in predictions[0]]

    data=fix_span_error(inputs['input_ids'][0],predicted_token_class)
    person_names = merge_person_names(data)
    arrvalues.append(person_names)

In [24]:
df['Name'] = arrvalues

In [25]:
def censor_last_name(data, column_to_censor, censor_char='*****'):
    censored_data = data.copy()
    censored_data[column_to_censor] = censored_data[column_to_censor].apply(lambda x: x.split()[0] + ' ' + censor_char * (len(x.split()) - 1))
    return censored_data #censor real Name

In [26]:
column_censor = "Name"

In [27]:
censored_df = censor_last_name(df, column_censor)#censor Last name

In [28]:
censored_df.head()

,text,OrderID,Platform,Name
0,ผู้รับ(TO) น.ส.ปณิธาน แก้วจา 47/20 ซ.ร่มโพธิ ถ...,221222BTVHAWY8,Shopee,น.ส.ปณิธาน *****
1,ผู้รับ(TO) ทวิรินทร์ สุรัชต์วิรากูล 406/500 คอ...,221222C3X56QEB,Shopee,ทวิรินทร์ *****
2,ผู้รับ(TO) ชมพูนุช ขจิตพรวดี 73/224 I Condo p...,221222AX1H2UTX,Shopee,ชมพูนุช *****
3,ผู้รับ(TO) ทวิรินทร์ สุรัชต์วิรากูล 406/500 คอ...,221222C3X56QEB,Shopee,ทวิรินทร์ *****
4,ผู้รับ(TO) ชมพูนุช ขจิตพรวดี ซ.สุขาอุปถัมภ์ 9 ...,221222AX1H2UTX,Shopee,ชมพูนุช *****

In [29]:
def has_english(text):
    for char in text:
        if char.isalpha() and char.isascii():
            return True
    return False

In [30]:
df['Has English'] = df['Name'].apply(has_english)

In [31]:
censored_df1 = censor_last_name(df, column_censor)
censored_df1.head()

,text,OrderID,Platform,Name,Has English
0,ผู้รับ(TO) น.ส.ปณิธาน แก้วจา 47/20 ซ.ร่มโพธิ ถ...,221222BTVHAWY8,Shopee,น.ส.ปณิธาน *****,False
1,ผู้รับ(TO) ทวิรินทร์ สุรัชต์วิรากูล 406/500 คอ...,221222C3X56QEB,Shopee,ทวิรินทร์ *****,False
2,ผู้รับ(TO) ชมพูนุช ขจิตพรวดี 73/224 I Condo p...,221222AX1H2UTX,Shopee,ชมพูนุช *****,False
3,ผู้รับ(TO) ทวิรินทร์ สุรัชต์วิรากูล 406/500 คอ...,221222C3X56QEB,Shopee,ทวิรินทร์ *****,False
4,ผู้รับ(TO) ชมพูนุช ขจิตพรวดี ซ.สุขาอุปถัมภ์ 9 ...,221222AX1H2UTX,Shopee,ชมพูนุช *****,False

In [32]:
filtered_df = df[df['Has English']] #fix only english name

In [33]:
filtered_df['Name'] = filtered_df['text'].str.extract(r'\(TO\)\s(.+?)\s\d')

C:\Users\10\AppData\Local\Temp\ipykernel_8900\1374611698.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Name'] = filtered_df['text'].str.extract(r'\(TO\)\s(.+?)\s\d')

In [34]:
filtered_df2 = filtered_df.drop(columns = "text")

In [35]:
filtered_df2.head()

            OrderID Platform                          Name  Has English
8    221228RY260PFR   Shopee                  Kirati Hashi         True
10   221228RY260PFR   Shopee                  Kirati Hashi         True
11   2212181WAPAX9N   Shopee  Naowarat Uthaisri บ้านเลขที่         True
13   2212181VAPAX9N   Shopee  Naowarat Uthaisri บ้านเลขที่         True
16  221214KTJVWEKXE   Shopee                      Laddawan         True

In [36]:
rows_to_replace = df.loc[df['Has English']]
row_index = rows_to_replace.index.to_numpy()
rows_to_replace['Name'] = rows_to_replace['text'].str.extract(r'\(TO\)\s(.+?)\s\d')
print(row_index)

[ 8 10 11 13 16 17]

C:\Users\10\AppData\Local\Temp\ipykernel_8900\688234455.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rows_to_replace['Name'] = rows_to_replace['text'].str.extract(r'\(TO\)\s(.+?)\s\d')

In [37]:
censored_df2 = censor_last_name(rows_to_replace, column_censor)#censor Last name
censored_df2 = censored_df2.drop(columns = "text")
censored_df2

            OrderID Platform                 Name  Has English
8    221228RY260PFR   Shopee         Kirati *****         True
10   221228RY260PFR   Shopee         Kirati *****         True
11   2212181WAPAX9N   Shopee  Naowarat **********         True
13   2212181VAPAX9N   Shopee  Naowarat **********         True
16  221214KTJVWEKXE   Shopee            Laddawan          True
17  221214KTJVWEKXE   Shopee            Laddawan          True

In [38]:
df.loc[row_index, 'Name'] = rows_to_replace['Name']

In [39]:
censored_df3 = censor_last_name(df, column_censor)#censor Last name
censored_df3 = censored_df3.drop(columns = "text")
censored_df3

            OrderID Platform                      Name  Has English
0    221222BTVHAWY8   Shopee          น.ส.ปณิธาน *****        False
1    221222C3X56QEB   Shopee           ทวิรินทร์ *****        False
2    221222AX1H2UTX   Shopee             ชมพูนุช *****        False
3    221222C3X56QEB   Shopee           ทวิรินทร์ *****        False
4    221222AX1H2UTX   Shopee             ชมพูนุช *****        False
5    221222BTVHAWY8   Shopee          น.ส.ปณิธาน *****        False
6    221228S31MWMBB   Shopee                 รุ้งเงิน         False
7    221216S7GFUD8J   Shopee                    คุณดา         False
8    221228RY260PFR   Shopee              Kirati *****         True
9    221228S31MWMEB   Shopee                 รุ้งเงิน         False
10   221228RY260PFR   Shopee              Kirati *****         True
11   2212181WAPAX9N   Shopee       Naowarat **********         True
12   221213J92K3P38   Shopee         โสมส่องหล้า *****        False
13   2212181VAPAX9N   Shopee       Naowarat **********         True
14  221213J92K3P338   Shopee         โสมส่องหล้า *****        False
15   221216S7GFUD8J   Shopee                    คุณดา         False
16  221214KTJVWEKXE   Shopee                 Laddawan          True
17  221214KTJVWEKXE   Shopee                 Laddawan          True
18   221215PP87QQQ2   Shopee            ปราโมทย์ *****        False
19   221204RDTR5WGS   Shopee            บวรรัตน์ *****        False
20   221215PP87QQQ2   Shopee            ปราโมทย์ *****        False
21   2212060F0PY5XQ   Shopee           ประกายดาว *****        False
22  221204RDTR!5WGS   Shopee  บวรรัตน์ ***************        False
23   221203NGVP6517   Shopee                      นัฎ         False
24   2212060F0PY5XQ   Shopee           ประกายดาว *****        False
25   221203NGVP6517   Shopee                      นัฎ         False
26   2212050U02245V   Shopee             ลลิตกร่ําชิต         False
27   2212060U02245V   Shopee              ลลิตกร *****        False
28   22120600QMHD9N   Shopee               มนตรี *****        False
29  2212060U44NINQU   Shopee            ลลิตกรอ่ําชิต         False
30   22120600QMHD9N   Shopee               มนตรี *****        False
31   2212060U44NNQU   Shopee            ลลิตกรอ่ําชิต         False
32   2212073MWQXQMU   Shopee              อัญชนา *****        False
33   22120736W3874V   Shopee      ตรีรักษ์แดงวิไลเลิศ         False
34   2212073MWQXQMU   Shopee              อัญชนา *****        False
35   22120736W3874V   Shopee      ตรีรักษ์แดงวิไลเลิศ         False
36   22120853S3B3WD   Shopee                   อรจิรา         False
37   2212084DJ5DQAQ   Shopee            ปฏิภาณเปียคํา         False
38   2212084DJ5DQAQ   Shopee            ปฏิภาณเปียคํา         False

In [40]:
df = df.drop(columns = 'Has English')

In [41]:
df['ที่อยู่'] = df['text'].str.split('\s+').str[3:]

In [43]:
df['ที่อยู่'] = df['ที่อยู่'].astype(str).str.replace('[', '').str.replace(']', '')
df['ที่อยู่'] = df['ที่อยู่'].astype(str).str.replace(',', '').str.replace("'", '')

C:\Users\10\AppData\Local\Temp\ipykernel_8900\516622218.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['ที่อยู่'] = df['ที่อยู่'].astype(str).str.replace('[', '').str.replace(']', '')

In [45]:
df.to_csv("OCR_shopee.csv",encoding='cp874', index=False)